name: schoolmanage
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intro_views_flutter: ^2.8.0
  file_picker: ^1.4.3+2
  camera: ^0.5.7+4
  random_color: ^1.0.3
  intl: ^0.16.1
  division: ^0.8.7+2
  flutter_spinkit: ^4.1.2
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+2
  # flutter_plugin_pdf_viewer:
  #   git:
  #     url: git://github.com/tamhiupanTam/flutter_plugin_pdf_viewer
  permission_handler: ^4.3.0
  image: ^2.1.4
  image_picker: ^0.6.3+4
  photo_view: ^0.9.2
  path_provider: ^1.6.1
  custom_radio_grouped_button: ^1.0.0
  google_sign_in: ^4.4.4

  # peek_and_pop: ^0.1.8
  # snap: ^1.0.0

  # State Management tools
  get_it: ^4.0.0
  provider: ^4.0.4

  # Icons
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.7.0

  # Firebase Dependencies
  firebase_auth: ^0.15.5+2
  firebase_core: ^0.4.4+2
  cloud_firestore: ^0.13.4
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  bottom_navy_bar: ^5.4.0

  rxdart: ^0.24.0
  fluttertoast: ^3.1.3
  firebase_storage: ^3.0.6
  cached_network_image: 2.0.0-rc.1
  firebase_messaging: 6.0.13
  flutter_local_notifications: 1.4.0
 


dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   rxdart: ^0.22.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Customicons
      fonts:
        - asset: assets/fonts/Customicons.ttf

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Nunito-Italic.ttf
